//! 布罗卡区模块
//! Broca's Area Module
//!
//! 布罗卡区是光脑方案的语言生成中枢，负责接收符号决策包，
//! 经过语义规划、神经生成和约束引导三个步骤输出自然语言。
//! Broca's Area is the language generation center of the Light-Brain Scheme,
//! responsible for receiving symbolic decision packages and outputting natural language
//! through three steps: semantic planning, neural generation, and constraint guidance.

mod semantic_planning;
mod generator;
mod constraint;
mod guardrails;
mod templates;

pub use semantic_planning::*;
pub use generator::*;
pub use constraint::*;
pub use guardrails::*;
pub use templates::*;

use crate::amygdala::StyleModifier;
use crate::veto::{VetoEngine, VetoSignal, VetoContext, VetoOperation};
use serde::{Deserialize, Serialize};

/// 布罗卡区 trait
/// Broca trait
///
/// 定义布罗卡区对外提供的标准接口。
/// Defines the standard interface exposed by Broca's Area.
pub trait Broca: Send + Sync {
    /// 生成自然语言回复
    /// Generate natural language response
    ///
    /// # 参数 / Arguments
    /// * `package` - 前额叶输出的符号决策包 / decision package from Prefrontal
    /// * `mode` - 创造性模式（严谨/日常/创意/反事实）/ creative mode
    ///
    /// # 返回 / Returns
    /// 生成的文本及其元数据。
    /// Generated text with metadata.
    fn generate(&self, package: &DecisionPackage, mode: &CreativeMode) -> GeneratedText;

    /// 应用护栏，返回 Logit Bias 向量
    /// Apply guardrails, return Logit Bias vector
    ///
    /// 在生成前调用，为词汇施加偏置以抑制或禁止特定词汇。
    /// Called before generation to apply biases that suppress or forbid specific tokens.
    fn apply_guardrails(&self, tokens: &[String], mode: &CreativeMode) -> Vec<f32>;

    /// 检查生成内容是否需要否决
    /// Check if generated content should be vetoed
    fn check_veto(&self, text: &str, context: &VetoContext) -> Option<VetoSignal>;
}

/// 符号决策包
/// Symbolic Decision Package
///
/// 前额叶融合各模块输出后生成的结构化指令。
/// Structured instruction generated by Prefrontal after fusing module outputs.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DecisionPackage {
    /// 意图类别
    pub intent: String,
    /// 事实内容（来自小脑检索结果）
    pub facts: Vec<FactItem>,
    /// 风格修饰符（来自杏仁核）
    pub style: StyleModifier,
    /// 是否触发澄清
    pub needs_clarification: bool,
    /// 澄清选项（若需要澄清）
    pub clarification_options: Vec<String>,
    /// 兜底动作（若无事实可依赖）
    pub fallback_action: FallbackAction,
    /// 接地置信度
    pub grounding_confidence: f32,
    /// 知识完整度
    pub knowledge_completeness: f32,
}

/// 事实条目
/// Fact item
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct FactItem {
    /// 主体
    pub subject: String,
    /// 属性
    pub attribute: String,
    /// 值
    pub value: String,
    /// 确定性
    pub certainty: f32,
    /// 来源
    pub source: String,
}

/// 兜底动作
/// Fallback action
#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum FallbackAction {
    /// 正常生成
    Normal,
    /// 回答"我不知道"
    Unknown,
    /// 使用澄清模板
    Clarify,
    /// 使用预设兜底回复
    Template(String),
}

/// 创造性模式
/// Creative mode
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum CreativeMode {
    /// 严谨推理：低温度，高门控
    Rigorous,
    /// 日常对话：中等温度，中等门控
    Daily,
    /// 头脑风暴：高温度，低门控
    Creative,
    /// 反事实想象：高温度，极低门控
    Counterfactual,
}

impl Default for CreativeMode {
    fn default() -> Self {
        CreativeMode::Daily
    }
}

impl CreativeMode {
    /// 获取温度参数 τ
    pub fn temperature(&self) -> f32 {
        match self {
            CreativeMode::Rigorous => 0.4,
            CreativeMode::Daily => 0.8,
            CreativeMode::Creative => 1.3,
            CreativeMode::Counterfactual => 1.2,
        }
    }

    /// 获取门控参数 γ
    pub fn gate(&self) -> f32 {
        match self {
            CreativeMode::Rigorous => 0.9,
            CreativeMode::Daily => 0.6,
            CreativeMode::Creative => 0.3,
            CreativeMode::Counterfactual => 0.1,
        }
    }

    /// 是否为软约束模式（创意/反事实下第二级护栏切换为软约束）
    pub fn is_soft_constraint_mode(&self) -> bool {
        matches!(self, CreativeMode::Creative | CreativeMode::Counterfactual)
    }
}

/// 生成结果
/// Generated text
#[derive(Debug, Clone)]
pub struct GeneratedText {
    /// 生成的文本
    pub text: String,
    /// 是否来自模板兜底
    pub is_fallback: bool,
    /// 使用的创造性模式
    pub mode: CreativeMode,
    /// 护栏触发记录
    pub guardrail_triggers: Vec<GuardrailTrigger>,
    /// 来源标记（哪些断言来自知识库）
    pub source_annotations: Vec<SourceAnnotation>,
}

/// 护栏触发记录
#[derive(Debug, Clone)]
pub struct GuardrailTrigger {
    pub token: String,
    pub tier: GuardrailTier,
    pub action: GuardrailAction,
}

/// 来源标注
#[derive(Debug, Clone)]
pub struct SourceAnnotation {
    pub text_span: String,
    pub source: String,
    pub certainty: f32,
}

/// 布罗卡区标准实现
/// Standard Broca implementation
#[derive(Debug)]
pub struct StandardBroca {
    planner: SemanticPlanner,
    generator: LanguageGenerator,
    guardrail: GuardrailManager,
    templates: TemplateManager,
    veto_engine: VetoEngine,
}

impl StandardBroca {
    /// 创建新的布罗卡区实例
    /// Create a new Broca instance
    pub fn new() -> Self {
        Self {
            planner: SemanticPlanner::new(),
            generator: LanguageGenerator::new(),
            guardrail: GuardrailManager::new(),
            templates: TemplateManager::new(),
            veto_engine: VetoEngine::new(),
        }
    }

    /// 使用自定义配置创建
    /// Create with custom configuration
    pub fn with_config(
        planner: SemanticPlanner,
        generator: LanguageGenerator,
        guardrail: GuardrailManager,
        templates: TemplateManager,
    ) -> Self {
        Self {
            planner,
            generator,
            guardrail,
            templates,
            veto_engine: VetoEngine::new(),
        }
    }
}

impl Default for StandardBroca {
    fn default() -> Self {
        Self::new()
    }
}

impl Broca for StandardBroca {
    fn generate(&self, package: &DecisionPackage, mode: &CreativeMode) -> GeneratedText {
        // 1. 语义规划
        let plan = self.planner.plan(package, mode);
        
        // 2. 若需要澄清或兜底，直接使用模板
        if package.needs_clarification {
            let text = self.templates.get_clarification(&package.clarification_options);
            return GeneratedText {
                text,
                is_fallback: true,
                mode: *mode,
                guardrail_triggers: Vec::new(),
                source_annotations: Vec::new(),
            };
        }
        
        if let FallbackAction::Template(template_key) = &package.fallback_action {
            let text = self.templates.get(template_key);
            return GeneratedText {
                text,
                is_fallback: true,
                mode: *mode,
                guardrail_triggers: Vec::new(),
                source_annotations: Vec::new(),
            };
        }
        
        // 3. 神经生成（调用 Python 侧 SLM）
        let candidates = self.generator.generate_candidates(&plan, mode);
        
        // 4. 约束引导与护栏
        let (best_candidate, triggers, annotations) = self.constraint_guided_selection(
            candidates,
            &plan,
            mode,
        );
        
        GeneratedText {
            text: best_candidate,
            is_fallback: false,
            mode: *mode,
            guardrail_triggers: triggers,
            source_annotations: annotations,
        }
    }

    fn apply_guardrails(&self, tokens: &[String], mode: &CreativeMode) -> Vec<f32> {
        self.guardrail.compute_logit_bias(tokens, mode)
    }

    fn check_veto(&self, text: &str, context: &VetoContext) -> Option<VetoSignal> {
        self.veto_engine.check_safety_only(context)
    }
}

impl StandardBroca {
    /// 约束引导的选择逻辑
    fn constraint_guided_selection(
        &self,
        candidates: Vec<String>,
        plan: &SemanticPlan,
        mode: &CreativeMode,
    ) -> (String, Vec<GuardrailTrigger>, Vec<SourceAnnotation>) {
        // 简化实现：选择第一个候选，实际应根据事实一致性和护栏评分
        let best = candidates.first().cloned().unwrap_or_else(|| {
            self.templates.get("fallback_unknown")
        });
        
        let triggers = self.guardrail.audit_triggers(&best);
        let annotations = self.annotate_sources(&best, &plan.facts);
        
        (best, triggers, annotations)
    }
    
    fn annotate_sources(&self, text: &str, facts: &[FactItem]) -> Vec<SourceAnnotation> {
        // 简化：检查文本中是否包含事实值，若有则标注来源
        let mut annotations = Vec::new();
        for fact in facts {
            if text.contains(&fact.value) {
                annotations.push(SourceAnnotation {
                    text_span: fact.value.clone(),
                    source: fact.source.clone(),
                    certainty: fact.certainty,
                });
            }
        }
        annotations
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_creative_mode_params() {
        assert_eq!(CreativeMode::Rigorous.temperature(), 0.4);
        assert_eq!(CreativeMode::Creative.gate(), 0.3);
        assert!(CreativeMode::Creative.is_soft_constraint_mode());
        assert!(!CreativeMode::Rigorous.is_soft_constraint_mode());
    }
}